### ISSUE TITLE
Python client: 'Repository' object has no attribute 'upload_file', 'get_content'

### ISSUE THREAD

**Issue by rishiraj** [tensorlakeai/indexify#331]
```
from indexify import IndexifyClient
client = IndexifyClient()
repo = client.get_repository("default")
repo.upload_file("songs.csv")
```
the above code throws error.

**Comment by lucasjacks0n** [comment]
Hey @rishiraj what is the error you are running into?

We are currently in the process of moving away from repositories. If you are using the latest version of indexify we will have the next upcoming release to our python client support these changes to our API.

What you can do in the meantime is clone the latest code for our python client and install from source

```shell
git clone https://github.com/tensorlakeai/indexify-python-client
cd indexify-python-client
pip install .
```

make these slight modifications to your code to upload a file
```python
from indexify import IndexifyClient
client = IndexifyClient()
client.upload_file("songs.csv")
```

**Comment by diptanu** [comment]
Fixed
