### ISSUE TITLE
Returning sources for a RAG

### ISSUE THREAD

**Issue by tzumby** [tensorlakeai/indexify#405]
Hi there,

I'm trying to return the content sources when running questions through a basic RAG. 
I found [this example in langchain](https://python.langchain.com/docs/use_cases/question_answering/sources#adding-sources) that looks very similar to the way you're retrieving answers in the [basic RAG example](https://getindexify.ai/usecases/rag/#perform-rag). 

```
def format_docs(docs):
    print(doc.page_content)
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain_from_docs = (
    {"context": retriever, "question": RunnablePassthrough.assign(context=(lambda x: format_docs(x["context"])))}
    | prompt
    | model
    | StrOutputParser()
)
```

When I try to print the context, I get a list of documents:

```
[Document(page_content="Content 1"), Document(page_content="Content 2")]
```

But when I add this:

```
rag_chain_with_source = RunnableParallel(
    {"context": retriever, "question": RunnablePassthrough()}
).assign(answer=rag_chain_from_docs)
```
I get an `TypeError: Object of type Document is not JSON serializable`

I'm actively debugging this and I feel I'm missing something very basic, but any help would be much appreciated!

**Comment by diptanu** [comment]
@tzumby Looking into this. Thanks for reporting.

**Comment by diptanu** [comment]
@tzumby This looks like an open issue in Langchain and a workaround is mentioned here - https://github.com/langchain-ai/langchain/issues/2222#issuecomment-1911839856

Please let me know if this solves your issue!

**Comment by tzumby** [comment]
Thank you @diptanu, I'm going to track this there. I'm taking a step back and trying to understand Langchain a bit more. Once I figure this out, I can contribute with some docs to Indexify if you think it would fit in with the rest of the resources.
