### ISSUE TITLE
`POST /namespaces/{}/extraction_graphs` returns 200 on conflict

### ISSUE THREAD

**Issue by grampelberg** [tensorlakeai/indexify#695]
The real problem here is that the original graph is not updated with the new values.

If we're being pedantic, I'd expect a 400 from this and a `PUT /namespaces/{}/extraction_graphs/{}` to be used for updates.

If we're going for something a little bit more usable from the client side, updating the definition would be a nice behavior.

I'm not sure which way I'd go. Being pedantic would likely be good long-term, that'll allow us to version the extraction graphs and then provide endpoints for latest vs older graphs depending on integrations. That said, it is a larger surface area for clients to manage.

**Comment by maxkozlovsky** [comment]
Yes I see the code returns success for an existing graph ignoring the updates. I'll fix it to return error code for now to remove the surprising behavior, and implement update of an existing graph eventually.

**Comment by maxkozlovsky** [comment]
fixed in #701
