### ISSUE TITLE
Update endpoint does not work 

### ISSUE THREAD

**Issue by sadath-12** [tensorlakeai/indexify#799]
I tried uploading docx and txt files at endpoint ``` /namespaces/{namespace}/extraction_graphs/{graph_name}/extract```
and when I tried to download it works (downloads the right file given the content_id)

When I try make changes on my file to update with endpoint ``` /namespaces/{namespace}/content/{content_id} ``` and try to redownload using same content_id . I see the same file with old content instead of new one . 

I'm assuming the update happens on same content id since there is no new content id response on PUT request

**Comment by maxkozlovsky** [comment]
Fixed in #822
