### ISSUE TITLE
Make catching optional

### ISSUE THREAD

**Issue by sadath-12** [tensorlakeai/indexify#935]
Initially just to be safe some users who run indexify centrally for all users might prefer to disable catching .
so there is no  chance for data leak. 

Also in lot of cases the cache actually is misleading where I used to get errors for the new code , I would have to delete the cache and retry to get changes into effect and let them work

**Comment by diptanu** [comment]
There is no caching happening at the moment when graphs are deployed in Indexify server. We cache results only when Graphs are run in-process on laptops by users to speed up testing.
