### ISSUE TITLE
Encrypt workflow code in the indexify server

### ISSUE THREAD

**Issue by sadath-12** [tensorlakeai/indexify#963]
I see currently indexify encodes the workflow code into the server as discussed with @diptanu , can we enable encrypting instead so companies can secure their workflow code as IP ?

**Comment by diptanu** [comment]
Doesnt' object stores do at rest encryption?

**Comment by diptanu** [comment]
Closing this as you can encrypt workflow code at rest on S3. no support on the OSS project is necessary. We encrypt everything in Tensorlake.
