### ISSUE TITLE
Allow passing headers to indexify server in workflow code

### ISSUE THREAD

**Issue by sadath-12** [tensorlakeai/indexify#967]
Allow custom headers to be passed whenever workflow code calls indexify server

**Comment by diptanu** [comment]
@sadath-12 Can you share the use case with us, and also an example of the header you want to pass in? How do you want the function to receive the header?

**Comment by sadath-12** [comment]
Since indexify do not support authentication . Let's say I use ingress auth https://kubernetes.github.io/ingress-nginx/examples/auth/basic/ , the way it authenticates the user is by asking the password in headers . So now I add indexify server behind ingress auth and that's the url I use in whenever I communication .. So that means `deploy` and `run` function will fail if headers are not supported.

If we consider executor too lets say its running in different machine than indexify-server , then executor also needs to provide headers to indexify https url. 

so the goal was  to support authentication here
