### ISSUE TITLE
How to extract relevant data stored in blob storage

### ISSUE THREAD

**Issue by sadath-12** [tensorlakeai/indexify#982]
Indexify stores the function outputs in s3 bucket , which also involves the input that is been sent . 
Let's say I'm ingesting a file along with metadata , I should be able to retrieve back the file along with its metadata for a specific `invocation_id` from the files indexify is ingesting into s3.

So , question is how do I analyse or make use of the files indexify is ingesting in s3

**Comment by stangirala** [comment]
When you say you have metadata that you would like to retrieve is there a reason you can't add it to the output of the function?

**Comment by sadath-12** [comment]
> When you say you have metadata that you would like to retrieve, is there a reason you can't add it to the output of the function?

sorry ,  I mean later how can I retrieve the file and metadata associated with an invocation_id

**Comment by stangirala** [comment]
right now we have a way to retrieve all outputs by graph/invocation ID so we if you add something to the Output you can just get it from there.

**Comment by sadath-12** [comment]
> right now we have a way to retrieve all outputs by graph/invocation ID so if you add something to the Output you can just get it from there.

ok which api ? Let's say my input object to workflow was 
```
filename
file
```

Given an invocation_id , i want to retrieve filename and file

**Comment by stangirala** [comment]
Could you write a small workflow example? That way it's clear what what filename is.

**Comment by sadath-12** [comment]
This is the object I pass to the workflow and goes over every function

```python
class PdfOutput(BaseModel):
    id: str
    file: IndexifyFile
    dbSchema: str  
    textchunk: List[TextChunk]
    doc: Document
    namespace: str
    pg: pgQuery
```

**Comment by stangirala** [comment]
But don't you already get this output using the graph get output method?

**Comment by sadath-12** [comment]
I tried ```/namespaces/{namespace}/compute_graphs/{compute_graph}/invocations/{invocation_id}/fn/{fn_name}/output/{id}``` It gives a file from bob_storage , which I cant read .

and ```/namespaces/{namespace}/compute_graphs/{compute_graph}/invocations/{invocation_id}/outputs``` gives some outcome of each function

**Comment by stangirala** [comment]
Ah got it! We want to support this, right now we are defaulting to serialization with cloudpickle and so without the python sdk code you can't de-serialize it. Right now could you use the python code directly to retrieve instead of using curl or another language?

**Comment by stangirala** [comment]
See https://github.com/tensorlakeai/indexify/issues/984

**Comment by diptanu** [comment]
JSON encoding for functions have landed.
