### ISSUE TITLE
Graph Context for sharing metadata across functions

### ISSUE THREAD

**Issue by diptanu** [tensorlakeai/indexify#983]
## Problem 
Some use-cases requiring sharing information between functions in a graph. Ex, in a PDF processing workflow - 

```python
def parse_docment(file: File) -> Document:
   # file contains metadata such as file name, url ,owner, etc, which needs to be 
  # written into databases but the output of this function only contains Pages 
  # and the file metadata is not shared
   ...
   
def chunk(doc: Document) -> List[Chunk]:
  ...

def embed_and_Write(chunk: Chunk) -> None:
   # Need the file name here so that it can be written into the vector db along side the chunk and embeddings
   # for citations
 ```
 
In this example we want some information from `File` to be available in downstream functions. It's possible to add these in the output of the first function but that becomes cumbersome and often repetitive if the information has to be shared across all functions. 

## Solution -

Provide a shared Dictionary to be mutated and read from every function. A new dictionary is initialized for every Graph invocation and is persisted by Indexify

```python
from indexify import get_graph_ctx


@indexify_function()
def parse_document(file: File) -> Document:
   ctx = get_graph_ctx()
   ctx.state["file_name"] = file.metadata["file_name"]
   ctx.state["some_other_metadata"] = file.some_other_metadata
   .....
   
   
@indexify_function()
def chunk_and_embed(chunk: Chunk) -> None:
   ctx = get_graph_ctx()
   file_name = ctx.state[“file_name”]
   vector_db.write(embeddings, metadata={"file_name": file_name}
```

Any function can get a reference to the Dictionary, and read/write to it to share information across them. In the backend we will implement persistence storage for them transparently.

**Comment by stangirala** [comment]
Should we call it KV cache or something along those lines. Also impose a size limit on the object?

**Comment by diptanu** [comment]
@stangirala The storage is going to be persistent and not a volatile cache. Under the hood we are going to use blob store so there is no limit per se.

**Comment by seriousben** [comment]
I like the feature!

Here are some thoughts about it. In the hope of providing possible improvements without muich bikeshedding.

## 1. Naming

I feel like the use of K/V or Dict is too generic. Especially if we introduced other SDKs.

Some possible alternatives:
- `graph invocation`
- `graph invocation context` <- My preference.
- `graph run context`
- `graph invocation data`
- `graph run data`

## 2. Conflict resolution

In the case of parallel execution of graph nodes, I think we will need to define how to deal with conflicts. i.e: if Node2 puts A=1 and Node3 puts A=2 at the same graph execution step. Otherwise we risk introducing unpredictability.

## 3. Extending the idea

If we went with `graph invocation context`, we could also provide metadata about the current invocation:

```py
class GraphInvocationContext(BaseModel):
    "id is the graph invocation id"
    id: str
    "data contains the user-managed graph specific data available to all of its functions."
    data: Dict[str, any] # or user_data
    # also :graph_version, invocation_number, started_at, image, image_version, ...
```

## 4. Python SDK API

It think it would be more natural to call a function on a graph or on the IndexifyFunction class.

Maybe:
```
Graph.current_context.id # return the invocation id
Graph.current_context.data # return the user managed data
# or when subclassing IndexifyFunction"
self.current_context.id
self.current_context.data
```

**Comment by diptanu** [comment]
@seriousben Great points. Extending your idea here to some concrete APIs - 

```python
from indexify import get_graph_context

@indexify_function()
def my_func(input): Output: 
  ctx: InvocationContext = get_graph_context()
  # ctx.invocation_id  - returns the current invocation id
  # ctx.graph_name - returns the graph name
  # ctx.set(key, value) -> Sets a Key where the last write wins 
  # ctx.get(key) -> (Value, Version)
  # ctx.set(key, value, version) -> CAS based PUT to support writes under high concurrency
 ```
 
 What do you think?

**Comment by seriousben** [comment]
> What do you think?
That is great.
We could make invocation_id and graph_name as readonly.

**Comment by seriousben** [comment]
For `Set`, would it make sense to detect when a key gets updated by two parallel invocations and prevent it?

Even if we did CAS based PUT (or mutexes), the joining function would still get a value that is would not be deterministic. So different runs of the same graph could result in a different value for the same key.

With all that said, maybe implementing a single way to Set and a single way to Get is sufficient for now. As long as the possible race condition is documented. Maybe that allows us to first implement a simpler API like: `ctx.user_data.key = value`.

**Comment by diptanu** [comment]
> For Set, would it make sense to detect when a key gets updated by two parallel invocations and prevent it?

CAS does that. It's the standard across every K/V api out there. And the default path is making the last write win if the user doesn't pass the version of the object that it updated.

**Comment by jpdeburgo** [comment]
I really like this idea.

I like your name suggestion @seriousben, `graph invocation context`

My only suggestion would be to make the context exist within the decorator and be an optional parameter to be able to be used like this:
```
@indexify_function()
def my_function(graph_ctx, other_param):
    print("Inside the function:", graph_ctx.get('text'), other_param)

@indexify_function()
def my_other_function(other_param):
    print("Inside the other function:", other_param)
```

This way you would not have to import it, but I'm okay without having it like this
